FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

WORKDIR /app/vittrigas  # 👈 Enter the inner vittrigas where manage.py is

RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "vittrigas.wsgi:application", "--bind", "0.0.0.0:8080"]
