FROM python:3.11-slim

# Prevent .pyc files
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY . .

# Move into the Django subfolder to run commands
WORKDIR /app/vittrigas

# Collect static files
RUN python manage.py collectstatic --noinput

# Run using Gunicorn
CMD ["gunicorn", "vittrigas.wsgi:application", "--bind", "0.0.0.0:8080"]
