# Generated by Django 5.2.1 on 2025-05-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
